# Generated by Django 6.0.3 on 2026-03-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("region", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=255)),
                ("submarket", models.CharField(max_length=100)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Office", "Office"),
                            ("Retail", "Retail"),
                            ("Industrial", "Industrial"),
                            ("Multifamily", "Multifamily"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sq_ft", models.IntegerField()),
                ("units", models.IntegerField(default=1)),
                ("year_built", models.IntegerField()),
                ("acres", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="analytics.market",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_name", models.CharField(max_length=200)),
                ("sq_ft_occupied", models.IntegerField()),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=12)),
                ("lease_end_date", models.DateField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="analytics.property",
                    ),
                ),
            ],
        ),
    ]
