# Generated by Django 6.0.3 on 2026-03-31 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="lease",
            name="monthly_rent",
        ),
        migrations.AddField(
            model_name="lease",
            name="lease_start_date",
            field=models.DateField(default="2026-01-01"),
        ),
        migrations.AddField(
            model_name="property",
            name="annual_capx_reserve",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="property",
            name="annual_opex_reserve",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="property",
            name="market_rent_per_sqft",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="property",
            name="misc_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lease",
            name="lease_end_date",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="analytics.propertytype",
            ),
        ),
        migrations.CreateModel(
            name="Submarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submarkets",
                        to="analytics.market",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="property",
            name="submarket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to="analytics.submarket",
            ),
        ),
    ]
