# Generated by Django 6.0.3 on 2026-05-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_propertytype_remove_lease_monthly_rent_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(fields=["lease_end_date"], name="idx_lease_end_date"),
        ),
        migrations.AddIndex(
            model_name="lease",
            index=models.Index(
                fields=["property", "lease_end_date"], name="idx_lease_property_enddate"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["market", "property_type"], name="idx_property_market_type"
            ),
        ),
    ]
